permalink: /:title

title: NineBall9
url: https://github.com/NineBall9/NineBall9.github.io.git
feed: /atom.xml
author_info: <a href="https://github.com/NineBall9/NineBall9.github.io.git">NineBall9</a>
